### ISSUE TITLE
To do

### ISSUE THREAD

**Issue by willu47** [nismod/git-novice#2]
- [x] Add Link to website notes so people can follow along
- [x] Slide 18 diagram of folder structure (difficult to visualise)
- [x] Slide 20. home directory = `C:/Users/will/planets`
- [x] `config - auto crlf` line ending on windows
- [x] Diagram of staging area and workflow earlier
- [x] Use windows text editor: `git config core.editor notepad`
- [x] colour output (contrast `$ input`
- [x] slide referencing NISMOD (change exercise from paper writing to code for nismod?)

**Comment by tomalrussell** [comment]
All done, current version here: https://nismod.github.io/git-novice/presentation/
